### ISSUE TITLE
Felling, Fiery Aura, Exchange, & Fracking not working on tool

### ISSUE THREAD

**Issue by mahilo3550** [TacoSupremes/WithSprinkles#11]
These enchantments cannot be applied to the All-in-one-Tool from Actually Additions, but the Multiple enchantment can. Any way you can fix this? It should register similar to a paxel as far as enchantments are concerned. Just sucks having to create a separate tool just to use Exchange.

**Comment by TacoSupremes** [comment]
I have fixed this bug and it will be in the newest release.
