### ISSUE TITLE
suggestion; items with multiple have a name per mode.

### ISSUE THREAD

**Issue by jonqrandom** [TacoSupremes/WithSprinkles#12]
as the title says - it'd make it easier to tell which mode you're in without needing the enchantment tooltip mod. it's just an idea, i understand it might not be possible or worth your time.

**Comment by TacoSupremes** [comment]
I not sure what you are asking for. I'm assuming that you want to be able to name the item multiple times in the anvil.

**Comment by jonqrandom** [comment]
sorry, yeah, that's right - so each mode of an item can have a different name.

**Comment by TacoSupremes** [comment]
I just implemented your idea into the mod. Sorry it took so long you probably forgot about this. Will be out in newest version coming this week.
