### ISSUE TITLE
[1.12] Lost Pages appear to generate loot chests when right-clicking on blocks.

### ISSUE THREAD

**Issue by elucent** [TacoSupremes/WithSprinkles#2]
After right clicking:
![image](https://user-images.githubusercontent.com/9532786/28251944-be9abd9e-6a56-11e7-90fb-b6b11b41067a.png)

Contents:
![image](https://user-images.githubusercontent.com/9532786/28251948-ce42890c-6a56-11e7-94a3-45153f8b9459.png)

**Comment by TacoSupremes** [comment]
I just fixed this bug in the 1.06 release. Thanks for reporting
